#!/bin/bash
# modules/02_squid_proxy.sh — Запуск Squid прокси с выбором анонимности (ИСПРАВЛЕНО)

run() {
    # ------------------------------------------------------------
    # 1. ИНИЦИАЛИЗАЦИЯ
    # ------------------------------------------------------------
    if [ -z "$HACK_KIT_ROOT" ]; then
        export HACK_KIT_ROOT="$HOME/TOR/hack_kit"
    fi

    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    CYAN='\033[0;36m'
    NC='\033[0m'

    echo -e "${YELLOW}[*] Запуск модуля Squid Proxy${NC}"
    echo "    Запускает HTTP/HTTPS прокси в изолированном контейнере"
    echo ""

    # Проверка Podman
    if ! command -v podman &> /dev/null; then
        echo -e "${RED}[✗] Podman не установлен!${NC}"
        return 1
    fi

    # ------------------------------------------------------------
    # 2. НАСТРОЙКИ
    # ------------------------------------------------------------
    echo "══════════════════════════════════════════════════════"
    echo "НАСТРОЙКИ ПРОКСИ"
    echo "══════════════════════════════════════════════════════"
    
    # ПОРТ
    echo -e "${BLUE}▶ ПОРТ ПРОКСИ${NC}"
    echo "   Номер порта, на котором будет доступен прокси"
    local PROXY_PORT="3128"
    read -p "Порт для прокси [${PROXY_PORT}]: " input_port
    PROXY_PORT=${input_port:-$PROXY_PORT}
    echo ""

    # СОХРАНЕНИЕ ДАННЫХ
    echo -e "${BLUE}▶ СОХРАНЕНИЕ ДАННЫХ${NC}"
    echo "   y - сохранять кэш и логи на диск"
    echo "   N - не сохранять (всё в RAM)"
    local SAVE_DATA="n"
    read -p "Сохранять кэш и логи? (y/N): " input_save
    SAVE_DATA=${input_save:-n}
    echo ""

    # ПРАВИЛА ДОСТУПА
    echo -e "${BLUE}▶ ПРАВИЛА ДОСТУПА${NC}"
    echo "   1) Только localhost"
    echo "   2) Все (allow all)"
    echo "   3) Твоя подсеть (10.0.4.0/24)"
    echo "   4) Свой вариант"
    local ACCESS_RULE="1"
    read -p "Выбери вариант [1]: " input_rule
    ACCESS_RULE=${input_rule:-1}
    echo ""

    # 🔥 РЕЖИМ АНОНИМНОСТИ
    echo -e "${BLUE}▶ РЕЖИМ АНОНИМНОСТИ${NC}"
    echo "   1) Обычный (прозрачный) — передает X-Forwarded-For и Via"
    echo "   2) Анонимный (Anonymous) — скрывает реальный IP, но видно что это прокси"
    echo "   3) ELITE (невидимый) — полностью скрывает факт использования прокси"
    echo ""
    local ANON_MODE="1"
    read -p "Выбери режим анонимности [1]: " input_anon
    ANON_MODE=${input_anon:-1}
    echo ""

    # ------------------------------------------------------------
    # 3. ПРОВЕРКА ПОРТА
    # ------------------------------------------------------------
    echo -e "${YELLOW}[*] Проверяем порт $PROXY_PORT...${NC}"
    if ss -tln | grep -q ":$PROXY_PORT "; then
        echo -e "${YELLOW}[!] Порт $PROXY_PORT занят. Ищу свободный...${NC}"
        local found=0
        for port in {3130..3150}; do
            if ! ss -tln | grep -q ":$port "; then
                PROXY_PORT=$port
                found=1
                echo -e "${GREEN}[✓] Найден свободный порт: $PROXY_PORT${NC}"
                break
            fi
        done
        if [ $found -eq 0 ]; then
            echo -e "${RED}[✗] Нет свободных портов${NC}"
            return 1
        fi
    else
        echo -e "${GREEN}[✓] Порт $PROXY_PORT свободен${NC}"
    fi
    echo ""

    # ------------------------------------------------------------
    # 4. ПОДГОТОВКА ДИРЕКТОРИЙ И КОНФИГА
    # ------------------------------------------------------------
    local CONTAINER_NAME="squid-proxy-$$"
    local SQUID_DIR=""
    local VOLUME_MOUNT=""
    local IMAGE="docker.io/sameersbn/squid:latest"
    local TMP_CONF=""
    
    local RUN_CMD="podman run -d --name $CONTAINER_NAME -p $PROXY_PORT:3128"
    
    if [[ "${SAVE_DATA,,}" == "y" ]]; then
        # --------------------------------------------------------
        # РЕЖИМ С СОХРАНЕНИЕМ ДАННЫХ
        # --------------------------------------------------------
        SQUID_DIR="$HACK_KIT_ROOT/data/squid/$CONTAINER_NAME"
        mkdir -p "$SQUID_DIR"/{cache,logs,conf}
        echo -e "${YELLOW}[*] Данные будут сохраняться в: $SQUID_DIR${NC}"
        
        local CONF_FILE="$SQUID_DIR/conf/squid.conf"
        
        # Базовый конфиг
        cat > "$CONF_FILE" << 'EOF'
# Squid config generated by hack_kit
http_port 3128

# Basic ACLs
acl localnet src 10.0.0.0/8
acl localnet src 172.16.0.0/12
acl localnet src 192.168.0.0/16
acl localnet src fc00::/7
acl localnet src fe80::/10

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 21
acl Safe_ports port 443
acl Safe_ports port 70
acl Safe_ports port 210
acl Safe_ports port 1025-65535
acl Safe_ports port 280
acl Safe_ports port 488
acl Safe_ports port 591
acl Safe_ports port 777
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
EOF

        # Правила доступа
        case "$ACCESS_RULE" in
            1)
                echo "http_access allow localhost" >> "$CONF_FILE"
                echo "http_access deny all" >> "$CONF_FILE"
                ;;
            2)
                echo "http_access allow all" >> "$CONF_FILE"
                ;;
            3)
                echo "acl mysubnet src 10.0.4.0/24" >> "$CONF_FILE"
                echo "http_access allow mysubnet" >> "$CONF_FILE"
                echo "http_access deny all" >> "$CONF_FILE"
                ;;
            4)
                read -p "Введи свою подсеть: " custom_subnet
                echo "acl custom_subnet src $custom_subnet" >> "$CONF_FILE"
                echo "http_access allow custom_subnet" >> "$CONF_FILE"
                echo "http_access deny all" >> "$CONF_FILE"
                ;;
        esac

        # 🔥 НАСТРОЙКИ АНОНИМНОСТИ (ИСПРАВЛЕНО!)
        case "$ANON_MODE" in
            2)
                echo "# Anonymous mode" >> "$CONF_FILE"
                echo "forwarded_for delete" >> "$CONF_FILE"
                echo "via off" >> "$CONF_FILE"
                ;;
            3)
                echo "# ELITE mode - полностью невидимый" >> "$CONF_FILE"
                echo "forwarded_for delete" >> "$CONF_FILE"
                echo "via off" >> "$CONF_FILE"
                echo "httpd_suppress_version_string on" >> "$CONF_FILE"
                # Отключаем все заголовки кэша
                echo "cache deny all" >> "$CONF_FILE"
                echo "cache_store_log none" >> "$CONF_FILE"
                echo "cache_log /dev/null" >> "$CONF_FILE"
                echo "access_log none" >> "$CONF_FILE"
                # Убираем X-Cache заголовки
                echo "request_header_access X-Cache deny all" >> "$CONF_FILE"
                echo "request_header_access X-Cache-Lookup deny all" >> "$CONF_FILE"
                echo "reply_header_access X-Cache deny all" >> "$CONF_FILE"
                echo "reply_header_access X-Cache-Lookup deny all" >> "$CONF_FILE"
                ;;
        esac

        # Остальной конфиг
        cat >> "$CONF_FILE" << 'EOF'

# Минимальные настройки для работы
cache_mem 8 MB
maximum_object_size_in_memory 32 KB

refresh_pattern ^ftp:           1440    20%     10080
refresh_pattern ^gopher:        1440    0%      1440
refresh_pattern -i (/cgi-bin/|\?) 0     0%      0
refresh_pattern .               0       20%     4320
EOF

        # Для ELITE режима не монтируем cache и logs
        if [ "$ANON_MODE" = "3" ]; then
            VOLUME_MOUNT="-v $SQUID_DIR/conf/squid.conf:/etc/squid/squid.conf"
        else
            VOLUME_MOUNT="-v $SQUID_DIR/conf/squid.conf:/etc/squid/squid.conf -v $SQUID_DIR/cache:/var/spool/squid -v $SQUID_DIR/logs:/var/log/squid"
        fi
        RUN_CMD="$RUN_CMD $VOLUME_MOUNT $IMAGE"
        
    else
        # --------------------------------------------------------
        # РЕЖИМ БЕЗ СОХРАНЕНИЯ (ВРЕМЕННЫЙ КОНФИГ)
        # --------------------------------------------------------
        echo -e "${BLUE}[*] Работаем полностью в RAM${NC}"
        
        TMP_CONF="/tmp/squid.conf.$$"
        
        # Базовый конфиг из образа
        podman run --rm "$IMAGE" cat /etc/squid/squid.conf > "$TMP_CONF" 2>/dev/null
        
        # Применяем правила доступа
        case "$ACCESS_RULE" in
            1) # localhost - уже есть в базовом конфиге
                ;;
            2) # allow all
                sed -i '/http_access deny all/i http_access allow all' "$TMP_CONF"
                sed -i 's/^http_access deny all/# http_access deny all/' "$TMP_CONF"
                ;;
            3) # подсеть
                sed -i '/http_access allow localhost/a acl mysubnet src 10.0.4.0/24\nhttp_access allow mysubnet' "$TMP_CONF"
                ;;
            4) # своя подсеть
                read -p "Введи свою подсеть: " custom_subnet
                sed -i "/http_access allow localhost/a acl custom_subnet src $custom_subnet\nhttp_access allow custom_subnet" "$TMP_CONF"
                ;;
        esac

        # 🔥 ПРИМЕНЯЕМ НАСТРОЙКИ АНОНИМНОСТИ (ИСПРАВЛЕНО!)
        case "$ANON_MODE" in
            2)
                echo "" >> "$TMP_CONF"
                echo "# Anonymous mode" >> "$TMP_CONF"
                echo "forwarded_for delete" >> "$TMP_CONF"
                echo "via off" >> "$TMP_CONF"
                ;;
            3)
                echo "" >> "$TMP_CONF"
                echo "# ELITE mode" >> "$TMP_CONF"
                echo "forwarded_for delete" >> "$TMP_CONF"
                echo "via off" >> "$TMP_CONF"
                echo "httpd_suppress_version_string on" >> "$TMP_CONF"
                # Отключаем всё что светит
                echo "cache deny all" >> "$TMP_CONF"
                echo "cache_store_log none" >> "$TMP_CONF"
                echo "cache_log /dev/null" >> "$TMP_CONF"
                echo "access_log none" >> "$TMP_CONF"
                echo "request_header_access X-Cache deny all" >> "$TMP_CONF"
                echo "request_header_access X-Cache-Lookup deny all" >> "$TMP_CONF"
                echo "reply_header_access X-Cache deny all" >> "$TMP_CONF"
                echo "reply_header_access X-Cache-Lookup deny all" >> "$TMP_CONF"
                # Минимум памяти
                echo "cache_mem 4 MB" >> "$TMP_CONF"
                ;;
        esac
        
        VOLUME_MOUNT="-v $TMP_CONF:/etc/squid/squid.conf"
        RUN_CMD="$RUN_CMD $VOLUME_MOUNT $IMAGE"
    fi

    # ------------------------------------------------------------
    # 5. УДАЛЯЕМ СТАРЫЙ КОНТЕЙНЕР
    # ------------------------------------------------------------
    if podman ps -a --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
        podman rm -f "$CONTAINER_NAME" >/dev/null 2>&1
    fi

    # ------------------------------------------------------------
    # 6. ЗАПУСК
    # ------------------------------------------------------------
    echo -e "${YELLOW}[*] Запускаем контейнер...${NC}"
    
    if ! eval $RUN_CMD >/dev/null 2>&1; then
        echo -e "${RED}[✗] Ошибка запуска контейнера${NC}"
        [ -n "$TMP_CONF" ] && rm -f "$TMP_CONF"
        return 1
    fi
    
    local CONTAINER_ID=$(podman ps -l -q)
    echo -e "${GREEN}[✓] Контейнер запущен. ID: $CONTAINER_ID${NC}"

    # ------------------------------------------------------------
    # 7. ПРОВЕРКА С УЧЕТОМ АНОНИМНОСТИ
    # ------------------------------------------------------------
    echo -e "${YELLOW}[*] Проверяем доступность прокси...${NC}"
    sleep 2

    if curl --proxy "http://localhost:$PROXY_PORT" --max-time 5 -s http://ifconfig.me > /dev/null; then
        echo -e "${GREEN}[✓] Прокси отвечает!${NC}"
        
        # Показываем, как видит прокси ifconfig.me в зависимости от режима
        echo ""
        echo -e "${CYAN}🔍 ПРОВЕРКА АНОНИМНОСТИ:${NC}"
        echo "------------------------"
        
        case "$ANON_MODE" in
            1)
                echo -e "${YELLOW}Режим: Обычный (прозрачный)${NC}"
                echo "Должны быть видны: X-Forwarded-For, Via, X-Cache"
                ;;
            2)
                echo -e "${YELLOW}Режим: Анонимный${NC}"
                echo "Должен быть виден Via, X-Cache, но НЕТ X-Forwarded-For"
                ;;
            3)
                echo -e "${YELLOW}Режим: ELITE (невидимый)${NC}"
                echo "Не должно быть НИЧЕГО: ни Via, ни X-Cache, ни X-Forwarded-For"
                ;;
        esac
        echo ""
        
        # Делаем тестовый запрос для демонстрации
        echo -e "${CYAN}📊 Результат ifconfig.me/all:${NC}"
        curl --proxy "http://localhost:$PROXY_PORT" --max-time 5 -s http://ifconfig.me/all 
        echo ""
        
    else
        echo -e "${RED}[!] Прокси не отвечает.${NC}"
        echo "    Логи: podman logs $CONTAINER_NAME"
    fi
    echo ""

    # ------------------------------------------------------------
    # 8. ВЫВОД ИНФОРМАЦИИ
    # ------------------------------------------------------------
    echo "══════════════════════════════════════════════════════"
    echo -e "${BLUE}🦑 SQUID PROXY ЗАПУЩЕН${NC}"
    echo "══════════════════════════════════════════════════════"
    echo "  ▶ Адрес: localhost:$PROXY_PORT"
    echo "  ▶ Контейнер: $CONTAINER_NAME"
    echo "  ▶ Режим сохранения: $([ "$SAVE_DATA" == "y" ] && echo "диск" || echo "RAM")"
    echo "  ▶ Правила доступа: $(case $ACCESS_RULE in 1) echo "localhost";; 2) echo "ALLOW ALL";; 3) echo "подсеть 10.0.4.0/24";; 4) echo "пользовательские";; esac)"
    echo "  ▶ Режим анонимности: $(case $ANON_MODE in 1) echo "Обычный";; 2) echo "Анонимный";; 3) echo "ELITE";; esac)"
    echo ""
    echo "  ▶ Примеры:"
    echo "     curl --proxy http://localhost:$PROXY_PORT http://ifconfig.me"
    echo "     curl --proxy http://localhost:$PROXY_PORT http://ifconfig.me/all"
    echo ""
    echo "  ▶ Для отладки: podman logs $CONTAINER_NAME"
    echo "══════════════════════════════════════════════════════"
    echo ""

    # ------------------------------------------------------------
    # 9. ЛОГИРОВАНИЕ
    # ------------------------------------------------------------
    log_experiment "02_squid_proxy" "прокси" "Запуск Squid на порту $PROXY_PORT (анонимность: $ANON_MODE)" \
                   "$CONTAINER_NAME" "$IMAGE" "успех" \
                   "Порт $PROXY_PORT, сохранение: $SAVE_DATA, анонимность: $ANON_MODE" "yes"

    # ------------------------------------------------------------
    # 10. ОЖИДАНИЕ ОСТАНОВКИ
    # ------------------------------------------------------------
    echo -e "${YELLOW}Нажми Enter, чтобы остановить прокси и удалить контейнер...${NC}"
    read

    echo -e "${YELLOW}[*] Останавливаем и удаляем контейнер...${NC}"
    podman stop "$CONTAINER_NAME" >/dev/null 2>&1
    podman rm "$CONTAINER_NAME" >/dev/null 2>&1
    
    [ -n "$TMP_CONF" ] && rm -f "$TMP_CONF"
    
    echo -e "${GREEN}[✓] Контейнер удалён${NC}"
}