[Interface]
Address = 10.66.66.1/24
PrivateKey = MGomrzRek35AZdpAX/Zvd7DLrfqxTE3MKrEN6L7DUHs=
ListenPort = 51820
PostUp = iptables -t nat -A POSTROUTING -s 10.66.66.0/24 -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.66.66.0/24 -o eth0 -j MASQUERADE

[Peer]
PublicKey = ysN7YuIHO5g4e3pL6kvX8o+Yw5s9x0ZgR3Li41lJ+EE=
AllowedIPs = 10.66.66.2/32
