[Interface]
Address = 10.66.66.1/24
PrivateKey = qATWqbK4j6m2DAkRqKPMRMFsEdr7cLJ4GlIH+LKPLW4=
ListenPort = 51820
PostUp = iptables -t nat -A POSTROUTING -s 10.66.66.0/24 -o eth0 -j MASQUERADE
PostDown = iptables -t nat -D POSTROUTING -s 10.66.66.0/24 -o eth0 -j MASQUERADE

[Peer]
PublicKey = S+YGEQtLkK8IYs8WUsuydi/RlnkdkVyQYm+/qYYo6zk=
AllowedIPs = 10.66.66.2/32
